base:
  project: wine-quality-project
  random_state: 42
  target_col: TARGET

data_source: # data source 
  remote_source: data_given/winequality.csv

load_data: # storing the data from data source
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.91
      l1_ratio: 0.83

model_dir: saved_models

reports:
  scores: report/scores.json
  params: report/params.json
